//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docu3c.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogFeed
    {
        public int ID { get; set; }
        public byte[] Title { get; set; }
        public byte[] Description { get; set; }
        public byte[] Tags { get; set; }
    }
}
