//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docu3c.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int CustomerID { get; set; }
        public int DocCustomerID { get; set; }
        public int AdvisorID { get; set; }
        public int PortfolioID { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerEmailID { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MartialStatus { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CustomerRelationShipID { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual PortfolioDetail PortfolioDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
