//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docu3c.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDetail
    {
        public int DocumentID { get; set; }
        public string DocCustomerID { get; set; }
        public int CustomerID { get; set; }
        public int PortfolioID { get; set; }
        public int UserID { get; set; }
        public string DocumentName { get; set; }
        public string DocumentURL { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Institution { get; set; }
        public string JSONFileIdentifier { get; set; }
        public string Reason { get; set; }
        public string FileStatus { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string CustomerName { get; set; }
        public bool IsCheckCompliance { get; set; }
        public string AccountNo { get; set; }
        public string ComplianceReason { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string ClassifyJSON { get; set; }
        public string AssetJSONIdentifier { get; set; }
        public string ComplianceJSONInput { get; set; }
        public string AccountType { get; set; }
        public string Client2Name { get; set; }
        public string ComplianceJSONOutput { get; set; }
        public string IsDOB { get; set; }
        public string IsAddress { get; set; }
        public string IsAccountNo { get; set; }
        public string IsCustomerName { get; set; }
        public string IsSSN { get; set; }
        public string IsAssetType { get; set; }
        public string IsSignature { get; set; }
        public string IsMutualViolation { get; set; }
        public string IsSubCategory { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual PortfolioDetail PortfolioDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
