//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docu3c.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class docu3cEntities : DbContext
    {
        public docu3cEntities()
            : base("name=docu3cEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryDetail> CategoryDetails { get; set; }
        public virtual DbSet<PortfolioDetail> PortfolioDetails { get; set; }
        public virtual DbSet<SubCategoryDetail> SubCategoryDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<CustomerDetail> CustomerDetails { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<DocumentIdentifier> DocumentIdentifiers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SubCategoryJSONIdentifier> SubCategoryJSONIdentifiers { get; set; }
        public virtual DbSet<BlogFeed> BlogFeeds { get; set; }
    }
}
